application: wataken44-hatebu-myhotentry
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /update
  login: admin
  script: main.application
- url: /.*
  script: main.application
